# coding=utf-8

"""urls for the dj-sponsoring package."""


from django.urls import path

from . import views


app_name = 'dj_sponsoring'
urlpatterns = [
    path("",
         view=views.SponsorListView.as_view(),
         name='sponsors-list',
         ),
    path("create",
         view=views.SponsorCreateView.as_view(),
         name='sponsor-create',
         ),
    path("<int:pk>",
         view=views.SponsorDetailView.as_view(),
         name='sponsor-detail',
         ),
    path("<int:pk>/update",
         view=views.SponsorUpdateView.as_view(),
         name='sponsor-update',
         ),
    path("<int:pk>/delete",
         view=views.SponsorDeleteView.as_view(),
         name='sponsor-delete',
         ),
    path("<int:pk>/images",
         view=views.SponsorImageListView.as_view(),
         name='sponsor-images-list',
         ),
    path("<int:pk>/images/create",
         view=views.SponsorImageCreateView.as_view(),
         name='sponsor-image-create',
         ),
    path("<int:pk>/files",
         view=views.SponsorFileListView.as_view(),
         name='sponsor-files-list',
         ),
    path("<int:pk>/files/create",
         view=views.SponsorFileCreateView.as_view(),
         name='sponsor-file-create',
         ),
    path("images/<int:pk>",
         view=views.SponsorImageDetailView.as_view(),
         name='sponsor-image-detail',
         ),
    path("images/<int:pk>/update",
         view=views.SponsorImageUpdateView.as_view(),
         name='sponsor-image-update',
         ),
    path("images/<int:pk>/delete",
         view=views.SponsorImageDeleteView.as_view(),
         name='sponsor-image-delete',
         ),
    path("files/<int:pk>",
         view=views.SponsorFileDetailView.as_view(),
         name='sponsor-file-detail',
         ),
    path("files/<int:pk>/update",
         view=views.SponsorFileUpdateView.as_view(),
         name='sponsor-file-update',
         ),
    path("files/<int:pk>/delete",
         view=views.SponsorFileDeleteView.as_view(),
         name='sponsor-file-delete',
         ),
]
