# coding=utf-8

"""urls for the dj-sponsoring package."""


from django.urls import path

from . import views


app_name = 'dj-sponsoring'
urlpatterns = [
    path("sponsors",
         view=views.SponsorListView.as_view(),
         name='sponsors-list',
         ),
    path("sponsors/create",
         view=views.SponsorCreateView.as_view(),
         name='sponsor-create',
         ),
    path("sponsors/<int:pk>",
         view=views.SponsorDetailView.as_view(),
         name='sponsor-detail',
         ),
    path("sponsors/<int:pk>/update",
         view=views.SponsorUpdateView.as_view(),
         name='sponsor-update',
         ),
    path("sponsors/<int:pk>/delete",
         view=views.SponsorDeleteView.as_view(),
         name='sponsor-delete',
         ),
    path("sponsors/<int:pk>/images",
         view=views.SponsorImageListView.as_view(),
         name='sponsor-images-list',
         ),
    path("sponsors/<int:pk>/images/create",
         view=views.SponsorImageCreateView.as_view(),
         name='sponsor-image-create',
         ),
    path("sponsors/images/<int:pk>",
         view=views.SponsorImageDetailView.as_view(),
         name='sponsor-image-detail',
         ),
    path("sponsors/images/<int:pk>/update",
         view=views.SponsorImageUpdateView.as_view(),
         name='sponsor-image-update',
         ),
    path("sponsors/images/<int:pk>/delete",
         view=views.SponsorImageDeleteView.as_view(),
         name='sponsor-image-delete',
         ),
    path("sponsors/documents",
         view=views.SponsorDocumentListView.as_view(),
         name='sponsor-documents-list',
         ),
    path("sponsors/documents/create",
         view=views.SponsorDocumentCreateView.as_view(),
         name='sponsor-document-create',
         ),
    path("sponsors/documents/<int:pk>",
         view=views.SponsorDocumentDetailView.as_view(),
         name='sponsors-document-detail',
         ),
    path("sponsors/documents/<int:pk>/update",
         view=views.SponsorDocumentUpdateView.as_view(),
         name='sponsors-document-update',
         ),
    path("sponsors/documents/<int:pk>/delete",
         view=views.SponsorDocumentDeleteView.as_view(),
         name='sponsors-document-delete',
         ),
]
