# Generated by Django 2.0.7 on 2018-08-23 11:55

import dj_sponsoring.models
import dj_sponsoring.storage
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Sponsor name')),
                ('summary', models.CharField(max_length=512, verbose_name='Sponsor summary')),
                ('description', markdownx.models.MarkdownxField(verbose_name='Sponsor description')),
                ('logo', models.ImageField(storage=dj_sponsoring.storage.OverwriteStorage(), upload_to=dj_sponsoring.models.sponsors_upload_to, verbose_name='Sponsor logo')),
                ('url', models.URLField(verbose_name='Sponsor url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sponsor creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Sponsor last modification date')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
                'ordering': ('name', '-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='SponsorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dj_sponsoring.models.sponsors_upload_to, verbose_name='Sponsor file')),
                ('name', models.CharField(max_length=128, verbose_name='Sponsor file name')),
                ('description', models.CharField(max_length=128, verbose_name='Sponsor file small description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sponsor file creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Sponsor file last modification date')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_sponsoring.Sponsor')),
            ],
            options={
                'verbose_name': 'sponsor file',
                'verbose_name_plural': 'sponsor files',
                'ordering': ('sponsor', 'name', 'created'),
            },
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=dj_sponsoring.models.sponsors_upload_to, verbose_name='Sponsor image')),
                ('alt', models.CharField(max_length=128, verbose_name='Sponsor image alternative text')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Sponsor image description text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sponsor image creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Sponsor image last modification date')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_sponsoring.Sponsor')),
            ],
            options={
                'verbose_name': 'sponsor image',
                'verbose_name_plural': 'sponsor images',
                'ordering': ('sponsor', 'created'),
            },
        ),
    ]
